### ISSUE TITLE
post process all phases

### ISSUE THREAD

**Issue by AutoTonner** [hanktseng131415go/RAMEM#4]

**Comment by hanktseng131415go** [comment]
Thank you for your response. Our plan is to create a unified scheme where we can deploy a single model to serve the intended purpose. Also, the separating phases will harm the purpose of having a seamless diagnosis in real-time. In terms of purposely separating systolic and diastolic, we have not seen a reason to do that to benefit our diagnosis as it simply divides a sequence process into sub-processes. If you need to be separated for your application, a modification of our code should work. Still, unfortunately, we cannot answer the difficulty because we have no background on your application. I hope this answer addresses some of your concerns.
